### ISSUE TITLE
Add more bed behavior

### ISSUE THREAD

**Issue by GoodLucky777** [PowerNukkit/PowerNukkit#620]
# ❇ Feature Request

### Missing Behavior
- [x] If the player's bed is broken or if the area around the bed is made unsuitable for respawning, it will show `tile.bed.notValid`. [#677]
  - [x] But it will check only when the player respawns. So, you can replace bed and respawns there.
- [x] If monster is near to bed, it will show `tile.bed.notSafe`. [#635]
  - [x] Check hostile only mobs and Piglin
- [x] Bed also explode in other custom dimensions. (So, only for Overworld) [#635]

### 💬 Anything else we should know?

https://minecraft.gamepedia.com/Bed
