### ISSUE TITLE
Implement Lead Things

### ISSUE THREAD

**Issue by good777LUCKY** [PowerNukkit/PowerNukkit#692]
# ❇ Feature Request

Implement Lead related things.

### 📝 Todo:
- [ ] If lead is attached, allow it to be moved by the player.
- [ ] Add method that leash entities.
- [ ] Add leash knot entity.
- [ ] Update ItemLead onActivate.

### 💬 Anything else we should know?

https://minecraft.gamepedia.com/Lead

It will help #582 (because of Balloon)
Able to leash boats.
